Repository kubernetes/sig-release, pull requests merged in 2018-04, with the labels that each got.

#110 Revised draft 1.11 release schedule.
  releases/release-1.11/release-1.11.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#108 v1.11 release team - add colemickens as shadow bug triage
  releases/release-1.11/release_team.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#114 1.11 features tracking spreadsheet added
  releases/release-1.11/release-1.11.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#117 release-1.11: Add Mike Arpaia as Release Notes Shadow
  releases/release-1.11/release_team.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#118 Docs team: correction, addition
  releases/release-1.11/release_team.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#119 111 new links
  releases/release-1.11/release-1.11.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#121 Add shadows for docs
  releases/release-1.11/release_team.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#123 Update CI Signal role in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#122 Correct final docs date
  releases/release-1.11/release-1.11.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Update link to slack channel
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 Add conditionally shortened code freeze to schedule.
  releases/release-1.11/release-1.11.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#131 Add Andrew Hatfield as Communications shadow
  releases/release-1.11/release_team.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#134 Added folks to OWNERS files who need to be able to approve things.
  OWNERS_ALIASES
  releases/release-1.11/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#136 Add release_notes_draft.md with proposed new tags
  releases/release-1.11/release_notes_draft.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#137 Update release-lead.md
  release-process-documentation/release-team-guides/release-lead.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#138 Update release-1.11.md
  releases/release-1.11/release-1.11.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
