Repository kubernetes/sig-release, pull requests merged in 2018-08, with the labels that each got.

#248 update alpha cadence
  releases/release-1.12/release-1.12.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#252 update release-team.md remove my middle name to better reflect my name in other places
  releases/release-1.12/release_team.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#253 Add old release branch CI removal as part of test-infra duties
  releases/release-1.12/release-1.12.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/S

#256 Update email address
  security-release-process-documentation/security-release-process.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#255 create test-infra role playbook
  release-team/role-handbooks/test-infra/OWNERS
  release-team/role-handbooks/test-infra/README.md
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/M

#239 Add notes on Milestone Maintainers
  release-team/README.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#250 Updates to the Release Notes Draft
  releases/release-1.12/release-notes-draft.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#262 add branch manager role handbook
  release-team/role-handbooks/branch-manager/OWNERS
  release-team/role-handbooks/branch-manager/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#266 security-release-process: document kubernetes-security GH managers
  security-release-process-documentation/security-release-process.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#240 move ephemera/issues.md to community repo devel guide
  ephemera/img/release-cycle.png
  ephemera/img/release-lifecycle.png
  ephemera/issues.md
  release-team/role-handbooks/bug-triage/README.md
  releases/release-1.12/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#268 remove references to status/approved-for-milestone
  release-team/role-handbooks/bug-triage/README.md
  releases/release-1.12/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#267 README: update meeting notes link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
